Update main_ecommerce-backend-himanshu.yml

diff --git a/.github/workflows/main_ecommerce-backend-himanshu.yml b/.github/workflows/main_ecommerce-backend-himanshu.yml
--- a/.github/workflows/main_ecommerce-backend-himanshu.yml
+++ b/.github/workflows/main_ecommerce-backend-himanshu.yml
@@ -16,12 +16,13 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: main
-          fetch-depth: 0 # Fetch all history to ensure all files are included
+          fetch-depth: 0
       - name: Debug directory structure
         run: |
           pwd
           ls -la
           ls -la Backend || echo "Backend directory not found"
+          ls -la Frontend || echo "Frontend directory not found"
       - name: Set up Node.js version
         uses: actions/setup-node@v3
         with:
@@ -33,8 +34,8 @@ jobs:
           npm run build --if-present
           npm run test --if-present
       - name: Zip artifact for deployment
-        working-directory: Backend
-        run: zip ../release.zip . -r
+        run: |
+          zip -r release.zip Backend/ Frontend/
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
